# Generated by Django 5.1.7 on 2025-03-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_produto_descrição_remove_produto_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descrição',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
